### ISSUE TITLE
Constants go outside of functions

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/HighLowNumberGuessingGame#3]
https://github.com/andulica/HighLowNumberGuessingGame/blob/3bffc708e5064450a4e59983e132dc31aef06123/Program.cs#L23

Place them in your class but not in a function so that you can access them from within other places of your code (which becomes important later on when you are working in larger projects) 
and also so that they only get assigned once and not every time the function gets called.

**Comment by andulica** [comment]
fixed this in the same time with the issue #2
