### ISSUE TITLE
This will generate a number between 0 and 100 👆 

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/HighLowNumberGuessingGame#5]
https://github.com/andulica/HighLowNumberGuessingGame/blob/2e16b1e9bf209ee0108084c1a77651e1e481dfd3/Program.cs#L13

Looking at the M$ documentation, this function includes the lower, but not the upper bound!
https://learn.microsoft.com/en-us/dotnet/api/system.random.next?view=net-8.0#system-random-next(system-int32-system-int32)

Another approach to generate a number between 1 and a given upper bound would be the overload that takes only one parameter, which generates a number between 0 and the given bound,
and then add one like
```int val = Random.Next(100) + 1; // --> 1 - 100```

**Comment by incredibleLeitman** [comment]
additionally, if you want to use the bounds later for console output to the user or range checking it would be wise to store those values as constants

**Comment by andulica** [comment]
I see . So Random.Next() has 3 overloaded methods in total. Also I see the point that you make on line 13. But I will go with Random.Next(min, max) simply because it makes more sense for me and I will change it to Random.Next(1, 101).
