### ISSUE TITLE
duplicated code

### ISSUE THREAD

**Issue by incredibleLeitman** [andulica/HighLowNumberGuessingGame#6]
https://github.com/andulica/HighLowNumberGuessingGame/blob/2e16b1e9bf209ee0108084c1a77651e1e481dfd3/Program.cs#L27-L31
https://github.com/andulica/HighLowNumberGuessingGame/blob/2e16b1e9bf209ee0108084c1a77651e1e481dfd3/Program.cs#L39-L43

Those two checks basically do the same and could be moved out of the surrounding conditions.
To make your code not dependent on which of the two variables (randomNumber and userGuess) is greater you could utilize the Math.Abs function:
https://learn.microsoft.com/en-us/dotnet/api/system.math.abs?view=net-7.0

**Comment by andulica** [comment]
I can't see how implementing Math.Abs would help me but in the same time I am aware that I am missing something. So Math.Abs(userGuess) would return the absolute value of that number. Say userGuess is 5 than 5 would be returned. How would that help me or what would be the benefit of having this method to return the very same value in this context. I could see the point if the userGuess could've been negative number but other than that I can't see it's use. Please correct me if I am wrong

**Comment by incredibleLeitman** [comment]
No, you are right, but this is exactly the point:
now you need to have two different calculations, depending on which value is greater.
using Math.Abs you can just substract one value from the other, always receiving a positive result,
which allows you to only have one generic calculation.

**Comment by andulica** [comment]
I was not reading the entire code to truly understand how Math.Abs() method would help me. I can see now that this is something that I keep doing. I will fix it this in the future ;) and thanks for advices
